### ISSUE TITLE
question for securing plugin applications

### ISSUE THREAD

**Issue by eujungkim** [cloudfoundry-incubator/cf-abacus#808]
I applied "secure=true" to cf-bridge and abacus-usage applications. I think it works well.

My uaa clients are like below.

1. abacus 
- scope : abacus.usage.write abacus.usage.read
- applied to : abacus-usage-collector, abacus-usage-meter, abacus-usage-accumulator, abacus-usage-aggregator, abacus-usage-reporting, abacus-cf-renewer 

2. abacus-linux-container
- scope : abacus.usage.linux-container.read abacus.usage.linux-container.write
- applied to : abacus-cf-applications 

3. abacus-service-bridge	
- scope : abacus.usage.write abacus.usage.read
- applied to : abacus-cf-services

Now I'll try to apply secure=true to following plugins.
- abacus-eureka-plugin
- abacus-account-plugin
- abacus-provisioning-plugin

For this, which scopes should be added to each uaa clients?
(I know that the account and provisioning plugins are just prototype, so I must recreate them.)

**Comment by hsiliev** [comment]
We typically use the following clients:
```yml
  - client_id: abacus.system
    authorities: abacus.usage.write,abacus.usage.read
    authorized_grant_types: client_credentials
    scope: abacus.usage.write,abacus.usage.read

  - client_id: cc
    authorities: cloud_controller.admin
    authorized_grant_types: client_credentials

  - client_id: application_bridge
    authorities: cloud_controller.admin_read_only
    authorized_grant_types: client_credentials

  - client_id: container
    authorities: abacus.usage.linux-container.write,abacus.usage.linux-container.read
    authorized_grant_types: client_credentials
    scope: abacus.usage.linux-container.write,abacus.usage.linux-container.read

  - client_id: object_storage
    authorities: abacus.usage.object-storage.write,abacus.usage.object-storage.read
    authorized_grant_types: client_credentials
    scope: abacus.usage.object-storage.write,abacus.usage.object-storage.read

  - client_id: hystrix
    authorities: abacus.system.read
    authorized_grant_types: client_credentials
    scope: abacus.system.read

  - client_id: broker_system
    authorities: clients.admin,reporting.agent.write,abacus.usage.write
    authorized_grant_types: client_credentials
    scope: clients.admin,reporting.agent.write,abacus.usage.write

  - client_id: broker_ui
    authorities:  abacus.usage.read,uaa.none
    authorized_grant_types: client_credentials
    scope: abacus.usage.read

  - client_id: broker_dashboard
    authorities: abacus.usage.read,abacus.usage.write,uaa.none
    authorized_grant_types: authorization_code,refresh_token
    redirect_uri: <url>
    scope: openid,cloud_controller_service_permissions.read,cloud_controller.read,abacus.usage.read,abacus.usage.write

  - client_id: service_bridge
    authorities: abacus.usage.write,abacus.usage.read
    authorized_grant_types: client_credentials
    scope: abacus.usage.write,abacus.usage.read
```
